### ISSUE TITLE
What is a white line appeared when I selected item ?

### ISSUE THREAD

**Issue by lion4ik** [bignerdranch/recyclerview-multiselect#16]
I use Theme.AppCompat.Light.NoActionBar with toolbar. How to remove this white line ? 
![device-2015-10-18-135704](https://cloud.githubusercontent.com/assets/2050372/10563332/0ac96f44-758f-11e5-8ecc-f6be699d1ff1.png)

**Comment by lion4ik** [comment]
Sorry It was my bug..

**Comment by ashrafamin91** [comment]
Dear @lion4ik , how did you solve the issue? I got it too.
