### ISSUE TITLE
Item ID is never used

### ISSUE THREAD

**Issue by chantellosejo** [bignerdranch/recyclerview-multiselect#25]
In MultiSelector, you're required to pass in a long id for selection (or it is taken from the holder itself using holder.getItemId()). This value is never actually used or saved anywhere. Either it's a bug, or it's unnecessary code.

**Comment by joshfriend** [comment]
Why did you close this issue? I'm wondering the same thing.

**Comment by chantellosejo** [comment]
@joshfriend I just pulled the entire library in and then deleted the value in my branch (and made some other changes). Technically the issue isn't resolved.
